# Generated by Django 5.0.1 on 2024-02-02 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingappointment', '0002_timeslot_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
