# Generated by Django 5.0.1 on 2024-02-02 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingappointment', '0003_timeslot_booked_timeslot_date_timeslot_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
