# Generated by Django 5.0.1 on 2024-02-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingappointment', '0004_remove_timeslot_date_remove_timeslot_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=50)),
                ('time', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00')], max_length=50)),
                ('clinic', models.CharField(choices=[('Health Plus Clinic', 'Health Plus Clinic'), ('Care Wellness Center', 'Care Wellness Center'), ('Harmony Medical Group', 'Harmony Medical Group'), ('Vitality Clinic', 'Vitality Clinic'), ('Wellness Solutions Center', 'Wellness Solutions Center'), ('Heartland Family Health', 'Heartland Family Health'), ('Precision Dental Care', 'Precision Dental Care'), ('Radiant Skin Clinic', 'Radiant Skin Clinic')], max_length=50)),
                ('doctor', models.CharField(choices=[('Dr. Emily Johnson', 'Dr. Emily Johnson'), ('Dr. Michael Smith', 'Dr. Michael Smith'), ('Dr. Sarah Davis', 'Dr. Sarah Davis'), ('Dr. Robert Anderson', 'Dr. Robert Anderson'), ('Dr. Jessica White', 'Dr. Jessica White'), ('Dr. Brian Miller', 'Dr. Brian Miller'), ('Dr. Jennifer Brown', 'Dr. Jennifer Brown'), ('Dr. Christopher Lee', 'Dr. Christopher Lee')], max_length=50)),
                ('Disease', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
