# Generated by Django 5.0.1 on 2024-02-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingappointment', '0005_booking_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
