# Generated by Django 5.0.1 on 2024-02-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingappointment', '0006_booking_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='completed',
        ),
    ]
